-- Raw match rows straight from the CSV: every column STRING, nothing coerced yet.
CREATE OR REPLACE EXTERNAL TABLE `PROJECT.bronze.ext_stored_matches` (
    is_finished       STRING,
    is_live           STRING,
    starts_in_seconds STRING,
    status_enum       STRING,
    id                STRING,
    sport             STRING,
    league            STRING,
    season            STRING,
    home_id           STRING,
    home_name         STRING,
    home_short_name   STRING,
    home_abbreviation STRING,
    home_logo_url     STRING,
    home_flag_url     STRING,
    away_id           STRING,
    away_name         STRING,
    away_short_name   STRING,
    away_abbreviation STRING,
    away_logo_url     STRING,
    away_flag_url     STRING,
    kickoff_utc       STRING,
    status            STRING,
    score_home        STRING,
    score_away        STRING,
    linescore_home    STRING,
    linescore_away    STRING,
    attendance        STRING,
    broadcast         STRING,
    has_odds          STRING,
    venue             STRING,
    updated_at        STRING,
    round             STRING,
    winner            STRING,
    score             STRING,
    linescore         STRING
)
OPTIONS (
    format                = 'CSV',
    uris                  = ['gs://BUCKET/stored_matches.csv'],
    skip_leading_rows     = 1,
    field_delimiter       = ',',
    quote                 = '"',
    allow_quoted_newlines = TRUE,
    encoding              = 'UTF-8'
);
